services:
  app:
    container_name: app
    image: foodlyfinds:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DATASOURCE_URL=${MYSQL_DATASOURCE_URL}
      - MYSQL_DATASOURCE_USERNAME=${MYSQL_DATASOURCE_USERNAME}
      - MYSQL_DATASOURCE_PASSWORD=${MYSQL_DATASOURCE_PASSWORD}
    depends_on:
      - db

  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATASOURCE_DB}
      - MYSQL_USER=${MYSQL_DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_DATASOURCE_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

#  db:
#    container_name: postgres_db
#    image: postgres:latest
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
#      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
#    volumes:
#      - ./postgres:/var/lib/postgresql/data