services:
  app:
    container_name: app
    image: foodlyfinds:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/foodlyfinds
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - app_data:/path/to/app/data

  db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foodlyfinds
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
    app_data:
    db_data: